version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: process.environment.POSTGRES_PASSWORD
      POSTGRES_DB: usersdb


